### PR TITLE
Applies theme similar to DSpace@MIT

### PR DESCRIPTION
**Pull request by matt-bernhardt**
Without a running local application, I'm flying somewhat blind - these have been proofed on static HTML, and should look like this:

quicksubmit

Please check the responsiveness of the navbar, specifically?

### CODE REVIEW

**Comment by JPrevost** [comment]
I'm reasonably certain the failed travis build is not related to this work ;)

The CodeClimate thing seems like a bug in their parser and not the code but if you disagree feel free to change it.

**Comment by matt-bernhardt** [comment]
Let me look at the CodeClimate error a bit more closely. Assuming the Ruby syntax is correct, the CSS syntax should work, but I'll poke on it a bit.

**Comment by JPrevost** [comment]
Yeah, I can't see what is wrong and it works. I suspect css-lint is confused that we've got ERB (embedded ruby) syntax in there. I'm inclined to ignore it.

I do see what appears to be a  1 pixel white border around the banner. As that may be a pain to track down without running code, I'm happy to take a closer look at that. Let me know.

**Comment by matt-bernhardt** [comment]
That 1px border is a feature, copied from DSpace@MIT and OA Stats. The rule comes from https://github.com/MITLibraries/QuickSubmit/blob/theme_changes/app/assets/stylesheets/application.css#L38-L39 - easy enough to remove, if you'd like it gone.

**Comment by JPrevost** [comment]
lol. I'm not gonna argue with what y'all have agreed upon. Looks good to me. I'm going to push this to a heroku instance so you can see it in action before we merge.

**Comment by matt-bernhardt** [comment]
I'm curious whether changing the CSS rule to `background-image: url('<%= asset_path 'banner.png' %>');` would cause CodeClimate to pass it - the W3C validator is fine with either syntax.

**Comment by JPrevost** [comment]
Hmmm. I'm concerned with the nested single quotes with that theory, but if you want to try more like:
`background-image: url("<%= asset_path 'banner.png' %>");` I'm not in any super rush to merge this to prevent your trying it out.

Also, this branch is live at: https://mit-quicksubmit.herokuapp.com

**Comment by matt-bernhardt** [comment]
It looks like the Ruby parser isn't running over that line of the stylesheet, fwiw - the deployed app still has the `<%= ... %>` block in it.

**Comment by JPrevost** [comment]
Ha. Let me debug locally and report back.

**Comment by matt-bernhardt** [comment]
Looks like the problem is that the CSS stylesheet has the wrong extension now, at least if I understand http://guides.rubyonrails.org/asset_pipeline.html#css-and-erb correctly

**Comment by JPrevost** [comment]
Yeah, I was about to post that I read that closer. Can you move your changes from application.css to layout.css.erb maybe? Or I can if you want to wash your hands of this.

**Comment by matt-bernhardt** [comment]
I'll do it - no worries

**Comment by JPrevost** [comment]
I'm guessing CodeClimate css-lint just skips `.erb` files ;)

**Comment by JPrevost** [comment]
Heroku is updated with the latest changes:
https://mit-quicksubmit.herokuapp.com

**Comment by JPrevost** [comment]
Thanks so much for this work!

It's ready to merge in my opinion. I'd normally squash commits now that we've had a chance to discuss in the PR. If you do that (which is not required, just suggested), please consider also adding an additional blank line to the bottom of `layout.css.erb`. Neither prevents merge in my opinion though so feel free to ignore both and merge at will.

:+1:

**Comment by JPrevost** [comment]
closes #53

**Comment by JPrevost** [comment]
I think I need to work on the flakey travis build separately. I've got this protected so it doesn't allow merges until that passes so I've restarted it. Sorry about that.

**Comment by matt-bernhardt** [comment]
No worries

**Pull request merged**
